<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mathtone.NeuralNetworks\Mathtone.NeuralNetworks.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mathtone.MIST" Version="2.5.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Prism.Core" Version="6.1.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Windows.Interactivity.WPF" Version="2.0.20525" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Controls\ClusteringDemoScreen.xaml.cs" />
    <Page Remove="Controls\ClusteringDemoScreen.xaml" />
  </ItemGroup>
  <UsingTask TaskName="Mathtone.MIST.NotificationWeaverBuildTask" AssemblyFile="..\packages\Mathtone.MIST.2.5.2\tools\net47\Mathtone.MIST.Builder.dll" />
  <Target Name="AfterBuild">
    <NotificationWeaverBuildTask TargetPath="$(TargetPath)" DebugMode="True" />
  </Target>
</Project>